Repository c3b5aw/webserv, pull requests merged in 2021-12, with the labels that each got.

#32 lint-update-1
  srcs/http/client.hpp
  srcs/http/request.hpp
  srcs/server/poll.hpp
Labels: enhancement

#38 request repr enhancement
  srcs/http/request.hpp
Labels: enhancement

#37 logger-uri-fix: fixed
  srcs/http/client.hpp
Labels: enhancement

#39 update request: add transfer-encoding chunked handling
  srcs/http/request.hpp
Labels: enhancement, http

#41 update request: update case insensitive issues
  srcs/http/client.hpp
  srcs/http/request.hpp
Labels: enhancement, http, error management

#43 Handle invalid request in request
  srcs/http/request.hpp
  srcs/models/enums.hpp
Labels: enhancement, http, error management

#48 response-headers
  Makefile
  srcs/conf/errors.hpp
  srcs/conf/parser.hpp
  srcs/consts.hpp
  srcs/http/client.hpp
  srcs/http/request.hpp
  srcs/http/response.hpp
  srcs/http/status.hpp
  srcs/main.cpp
  srcs/models/IBlock.hpp
  srcs/models/IServer.hpp
  srcs/models/consts.hpp
  srcs/models/enums.hpp
  srcs/server/instance.hpp
  srcs/server/poll.hpp
  tests/configs/vhost_error.conf
  tests/www/html/401.html
Labels: enhancement

#51 upload_pass && nested_locations
  srcs/conf/enums.hpp
  srcs/conf/errors.hpp
  srcs/conf/parser.hpp
  srcs/models/IBlock.hpp
  srcs/models/ILocation.hpp
  srcs/models/IServer.hpp
  tests/configs/errors/location_nested.conf
Labels: enhancement

#53 GET
  srcs/conf/enums.hpp
  srcs/conf/errors.hpp
  srcs/conf/parser.hpp
  srcs/consts.hpp
  srcs/http/codes.hpp
  srcs/http/request.hpp
  srcs/http/response.hpp
  srcs/models/IBlock.hpp
  srcs/models/ILocation.hpp
  srcs/models/IServer.hpp
  srcs/server/autoindex.hpp
  srcs/server/instance.hpp
  tests/configs/default.conf
  tests/configs/errors/empty.conf
  tests/scripts/stress_test.py
  tests/www/html/index.html
  tests/www/html/test.html
Labels: enhancement

#58 Delete
  srcs/conf/parser.hpp
  srcs/http/enums.hpp
  srcs/http/response.hpp
  srcs/models/IBlock.hpp
  srcs/models/ILocation.hpp
  srcs/models/IServer.hpp
Labels: enhancement

#61 Session
  Makefile
  README.md
  srcs/consts.hpp
  srcs/http/client.hpp
  srcs/http/request.hpp
  srcs/http/response.hpp
  srcs/http/session.hpp
  srcs/http/utils.hpp
  srcs/models/IServer.hpp
  srcs/server/poll.hpp
  tests/www/php/webserv_session_test.php
Labels: enhancement
